baseURL = "https://www.giltedged.studio/"
title = "Gilt Edged Studio"
author = "Daniel O'Driscoll"
copyright = "Daniel O'Driscoll"
paginate = 5
languageCode = "en-us"
enableInlineShortcodes = true
theme = "tailwind"

[markup]
[markup.highlight]
  # lineNos = true
  noClasses = false

[params]
  # SEO keywords and description.
  keywords = "agent-based models, modern monetary system, UK Gilts"
  subtitle = "A data analysis project"
  # dir name of your blog content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"
  showReadingTime = false
  toc = false
  favicon = "/static/favicon.ico" # Path to favicon file  

  [params.header]
    logo = "development_icon.png"

  [params.footer]
    since = 2023
    poweredby = false

[menu]

  [[menu.main]]
    identifier = "post"
    name = "Post"
    pageRef = "/posts"
    weight = 0

  [[menu.main]]
    identifier = "about"
    name = "About"
    pageRef = "/about"
    weight = 1

  [[menu.main]]
    identifier = "EMS"
    name = "EMS"
    pageRef = "/early-modern-system"
    weight = 2

  [[menu.main]]
    identifier = "resource"
    name = "Resource"
    pageRef = "/resource"
    weight = 3

  [[menu.main]]
    identifier = "custom"
    name = "Custom Made"
    pageRef = "/custom-made"
    weight = 4

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[services]

  [services.googleAnalytics]
    ID = "G-D7PXB7SQCH"

[[redirects]]
  from = "/**"  
  to = "/404.html"
  status = 404
